[tool.bandit.assert_used]
skips = ["*/test_*.py", "*/test_*.py"]

[tool.black]
line-length = 88
preview = true

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true
strict_equality = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true


[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "tests",
]
addopts = "--cov=src/ -v --cov-report=term-missing --no-cov-on-fail"
